# -*- coding: utf-8 -*-
"""mse using regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zdGu-iqptVx3EEXlC0YEIWmZn4FyGl0E
"""

import pandas as pd
import numpy as np

column_names = ['user id','movie id','rating','timestamp']
u_data = pd.read_csv('u.data', sep='\t',header=None,names=column_names)
u_data

c = 'movie id | movie title | release date | video release date | IMDb URL | unknown | Action | Adventure | Animation | Children | Comedy | Crime | Documentary | Drama | Fantasy | Film-Noir | Horror | Musical | Mystery | Romance | Sci-Fi | Thriller | War | Western'
column_names2 = c.split(' | ')
data_items = pd.read_csv('u.item', sep='|',header=None,names=column_names2,encoding='latin-1')
data_items

column_names3 = ['user id','age','gender','occupation','zip-code']
u_user= pd.read_csv('u.user', sep='|',header=None,names=column_names3)
u_user

new_df= pd.merge(u_data, data_items[['movie id', 'movie title']], how='left', left_on='movie id', right_on='movie id')
new_df= pd.merge(new_df,u_user,how='inner',on='user id')
new_df

import numpy as np
from sklearn.metrics import mean_squared_error, log_loss
from sklearn.linear_model import LinearRegression, LogisticRegression

column_names = ['user id','movie id','rating','timestamp']
u1_base = pd.read_csv('u1.base', sep='\t',header=None,names=column_names)
u1_base

x_train1= u1_base[['user id','movie id']]
x_train1

y_train1=u1_base[['rating']]
y_train1

column_names = ['user id','movie id','rating','timestamp']
u1_test = pd.read_csv('u1.test', sep='\t',header=None,names=column_names)
u1_test

x_test1= u1_test[['user id','movie id']]
x_test1

y_test1= u1_test[['rating']]
y_test1

lr= LinearRegression()
lr.fit(x_train1,y_train1)
train_score = mean_squared_error(y_train1, lr.predict(x_train1))
test_score = mean_squared_error(y_test1, lr.predict(x_test1))
train_score, test_score